// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products/": {
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/available": {
      "get": {
        "summary": "getProductsAvailableList",
        "description": "",
        "operationId": "getProductsAvailableList.get.products/available",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{id}/": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{id}/",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "article": {
          "title": "Product.article",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "article",
        "title",
        "description",
        "price",
        "image"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductCount": {
      "properties": {
        "productId": {
          "title": "ProductCount.productId",
          "type": "string"
        },
        "count": {
          "title": "ProductCount.count",
          "type": "number"
        }
      },
      "required": [
        "productId",
        "count"
      ],
      "additionalProperties": false,
      "title": "ProductCount",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};